name: 'HTML5 Validator'
description: 'Checks HTML5 Syntax'
author: Cyb3r-Jak3
branding:
  icon: 'award'  
  color: 'green'
inputs:
  Root:  # id of input
    description: 'Path of the files to test'
    required: true
    default: '.'
outputs:
  result: # id of output
    description: 'The result of the command'
runs:
  using: 'docker'
  image: 'Dockerfile'