name: Build Test

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .